export const Languages = 
    {
        ch:{
          logintitle:"Wosay",
          registertitle:"Wosay",
          newversionrel: "要安装新版",
          username:"用户名",
          password:"密码",
          loginpassword:"登录密码",
          usernameholder:"请输入用户名或邮箱",
          storeondevice: "记住用户", 
          passwordholder:"请输入8-20位密码",
          passwordlengthwrong: "密码不是8-20位!",
          passwordagainlengthwrong: "确认密码不是8-20位!",
          loginbtntxt:"登录",
          notregisteredyet: "还没有账号? 马上",
          pleaseregister: "注册",
          forgotpassword:"忘记密码",
          forgotpasswordReset:"找回",
          registerusername: "用户名",
          registeremail:"邮箱",
          registerpassword:"密码",
          registerpasswordagain: "确认密码",
          sponsor:"邀请人",
          sponsorholder: "请输入邀请码",
          district:"地区",
          registerbtn: "注册",
          hasaccount:"已有账号？直接",
          allrequiredfields: "请输入所有要求的栏目!",
          bitwalletcreateerror: "比特钱包生成错误, 请再试!",
          registersuccess: "注册成功！请检查您的邮件!",
          twopwdsnotmatch: "两个密码不一致!",
          inputusernameandpwd: "请填入用户名和密码!",
          inputusernameregister: "请输入用户名",
          setpassword: "设置密码",
          nosponsor: "无推荐人",
          thisemail: "这个邮箱: ",
          emailexists: "已经存在，请换一个邮箱!",
          donotexist: "不存在",
          thisusername: "这个用户名",
          usernameexists: "已经存在，请换一个用户名",
          china: "中国",
          canada: "加拿大",
          usa: "美国",
          singapore: "新加坡",
          korea: "韩国",
          malaysia: "马拉西亚",
          thailand: "泰国",
          selectcountry: "选地区...",
          selectbuyerid: "选用户名...",
          usernamepwderror: "用户名或密码错误!",
          inputcorrectussernamepwd: "如果注册过了, 请输入正确的用户名和密码!",
          loginfailedretry: "登录失败, 请再试一次!",
          serveremptyvalueretry: "服务器返回空值, 回键重试",
          scan: "扫一扫",
          getpay: "收款",
          tabmine:"设置",
          memberinactive:"未激活",
          memberregular: "普通会员",
          membermanager:'经理',
          membersenior:"高级经理",
          datarefreshed: "数据更新完成",
          memberceo:"总裁",////welcome to tern screen
          continuebtn:"继续",
          donecopy:"完成了复制",
          retrybtn:"再试",
          submitbtn:"提交",
          msgtitle:"注意:",
          pastebtn:"粘贴",
          skipbtn: "跳过",
          clearbtn:"清除",
          copybtn: "复制",
          applybtn:"申请",
          amount:"数量",//bonus view
          buyerId: "用户名",
          assettype:"资产类型",
          bonus: "红包",
          createdate:"生成日期",
          comment:"说明",
          status: "状态",//confirmOmniTransaction
          confirmtrantitle: "继续交易",
          wifinotgood:"网络不佳，稍后再试!",
          wifinotfine:"网络不给力，稍后再试",
          statuscode: "状态码: ",
          wiftnotpowerful:"网络不给力",
          retry: "重试",//confirmStellarTransaction
          findpassword:"找回密码",
          emailinvaid: "电邮格式不对!",
          checkemailtofindpwd:"请检查您的电子邮件, 找回密码!",
          plsinputemail:"请输入您的电子邮件!",
          email:"电子邮箱",
          inputemail: "请输入邮箱",
          feedbacktitle:"信息返馈",//imort lost wallet
          inputcorrectprivatekey:"请输入正确的私钥!",
          success: "成功:",
          inputfeedback: "请输入返馈信息",
          nobtcwalletfound:"本机上没有找到您的比特钱包，请输入您的比特私钥恢复钱包:", //my memberinfo
          mymemeberinfo: "我的社区",
          mysponsormember:"我推荐的伙伴",
          bonuslist: "奖金记录",
          memberachievement:"个人业绩",
          teamachievement:"团队业绩",
          teamsize:"团队人数",
          newachievement:"新增业绩",
          transhistory:"交易历史",//omni trans history
          blocknumber:"区块号",
          blocktimestamp:"时间",
          gaseused:"交易费",
          confirmations:"已确认数",
          transnotfound: "没有找到交易!",
          notprovided: "未提供",
          notconfirmed: "未确认",
          confirmed: "已确认",
          confirmedornot: "确认",
          invalid:"无效",
          valid: "有效",
          isvalid:"是否有效",
          invalidreason: "无效原因",
          settings: "设置",
          mysponsor: "邀请",
          setchangetradepin: "设置修改交易密码",
          feedback: "信息返馈",
          version: "版本",
          exit: "退出",
          sharebtn: "分享",
          privatekey: "私钥",
          copyboth: "两个一起复制",
          inviteregister:"邀请注册",//Referral
          inviteshare: "邀请分享",
          scantoregister:"扫码注册",
          sponsorcode: "邀请码",
          invite: "邀请",
          scansponsorcode: "扫码邀请码",
          invitetodownload: "邀请下载",
          scantodownload: "扫码下载",
          memotitle:"备注",
          cancel: "取消",
          date: "日期",
          checkwifi: "请检查网络!",
          plsretry: "请再试.",
          inputpassword: "请输入登录密码",
          tradepin: "交易密码",
          language: "语言",
          iknow: "知道了",
          goodnews: "喜讯"

        },
        en:{
          logintitle:"Wosay",
          registertitle:"Wosay",
          newversionrel: "There is a new version",
          username:"UserName",
          loginpassword:"Login Password",
          password:"Password",
          storeondevice: "Save user", 
          usernameholder:"UserName or Email",
          passwordholder:"8-20 characters",
          passwordlengthwrong: "Password length is not 8-20 characters!",
          passwordagainlengthwrong: "The 2nd Password length is not 8-20 characters!",
          loginbtntxt:"Login",
          notregisteredyet: "Not registered yet?",
          pleaseregister: "Register",
          forgotpassword:"Forgot password",
          forgotpasswordReset:"Reset Password",
          registerusername: "UserName",
          registeremail:"Email",
          registerpassword:"Password",
          registerpasswordagain: "Password Again",
          sponsor:"Sponsor",
          sponsorholder: "Sponsor's code",
          district:"Country",
          registerbtn: "Register",
          allrequiredfields: "Please input all required fields!",
          bitwalletcreateerror: "Bitcoin wallet not created, please retry!",
          registersuccess: "Registered successfully, please check your email!",
          twopwdsnotmatch: "The two passwords do not match!",
          inputusernameandpwd: "Please input user name & password!",
          inputusernameregister: "Please input user name",
          setpassword: "Password",
          nosponsor: "No sponsor",
          thisemail: "This email: ",
          emailexists: " exists, please change another one!",
          donotexist: " does not exist!",
          thisusername: "This username: ",
          usernameexists: "exists, please change another one",
          china: "China",
          canada: "Canada",
          usa: "USA",
          singapore: "Singapore",
          korea: "Korea",
          malaysia: "Malaysia",
          thailand: "Thailand",
          selectcountry: "Select country...",
          selectbuyerid: "Select buyer...",
          usernamepwderror: "Wrong user name or password!",
          checkwifi: "Please check network connection!",
          inputcorrectussernamepwd: "If registered, please input username & password!",
          loginfailedretry: "Login failed, please retry!",
          hasaccount:"Already registered? ",//assets screen
          scan: "Scan",
          getpay: "Receive",
          tabmine:"Settings",
          memberinactive:"Not activated",
          memberregular: "Regular Member",
          membermanager:'Manager',
          membersenior:"Senior Manager",
          datarefreshed: "Data updated.",
          serveremptyvalueretry: "Server returned empty value, back & retry",
          memberceo:"CEO",//welcome to tern screen
          continuebtn:"Continue",
          donecopy:"Copied",
          retrybtn:"Retry",
          submitbtn:"Submit",
          msgtitle:"Attention:",
          pastebtn:"Paste",
          skipbtn: "Skip",
          clearbtn:"Clear",
          copybtn: "Copy",
          applybtn:"Apply",
          amount:"Amount",//bonus view
          buyerId: "User Name",
          assettype:"Asset Type",
          bonus: "Bonus",
          createdate:"Date Created",
          comment:"Description",
          status: "Status",//confirmOmniTransaction
          confirmtrantitle: "Transaction",
          wifinotgood:"Poor network, please try later!",
          wifinotfine:"The network is poor, please try later!",
          statuscode: "Status code: ",
          wiftnotpowerful:"The network is poor",
          retry: "Retry",//confirmStellarTransaction
          findpassword:"Reset password",
          emailinvaid: "Email format not correct!",
          checkemailtofindpwd:"Please check your email, reset password!",
          plsinputemail:"Please input your email",
          email:"Email",
          inputemail: "Please input email",
          feedbacktitle:"Feedback",//imort lost wallet
          inputcorrectprivatekey:"Please input correct private key!",
          success: "Success:",
          inputfeedback: "Please input feedback",
          nobtcwalletfound:"Your Bitcoin wallet not found，please input private key to recover:", //my memberinfo
          mymemeberinfo: "Member info",
          mysponsormember:"My sponsorship",
          bonuslist: "Bonus",
          memberachievement:"My Perf",
          teamachievement:"Team Perf",
          teamsize:"TeamSize",
          newachievement:"New Perf",
          transhistory:"Transactions",//omni trans history
          blocknumber:"Block number",
          blocktimestamp:"Timestamp",
          gaseused:"Gas used",
          confirmations:"Confirmations",
          transnotfound: "Transaction not found!",
          notprovided: "Not provided",
          notconfirmed: "Unconfirmed",
          confirmed: "Confirmed",
          confirmedornot: "Confirmation",
          invalid:"Invalid",
          valid: "Valid",
          isvalid:"Validity",
          invalidreason: "Invalid Reason",
          settings: "Settings",
          mysponsor: "My referral link",
          setchangetradepin: "Change Transact PIN",
          feedback: "Feedback",
          version: "Version",
          exit: "Exit",
          sharebtn: "Share",
          privatekey: "Private Key",
          copyboth: "Copy Both",
          inviteregister:"My referral link",//Referral
          inviteshare: "Share & Refer",
          scantoregister:"Scan to register",
          sponsorcode: "Sponsor Code",
          invite: "Referral",
          scansponsorcode: "Scan sponsor code",
          invitetodownload: "Refer & download",
          scantodownload: "Scan to download",
          memotitle:"Memo",
          cancel: "Cancel",
          date: "Date",
          plsretry: "Please retry.",
          inputpassword: "Please input login password",
          tradepin: "PIN",
          language: "Language",
          iknow: "Got it",
          goodnews: "Good News"
        }
    };